datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://rm-bp1k0ef85lmpf2821zo.mysql.rds.aliyuncs.com/clwz?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  username: root
  password: Ali123!@#

server:
  port: 8080
