delete from violation_type;
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day) values (1,'闯红灯',6,200,0);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (2,'无证驾驶',0,500,15);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (3,'超载或超员',6,300,0);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (4,'使用伪造驾驶证',6,1000,15);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (5,'超速行驶',6,500,0);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (6,'驾驶拼装或报废机动车',12,1500,5);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (7,'记满12分继续驾车',12,2000,15);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (8,'酒驾',3,500,0);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (9,'醉驾',4,2000,3);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (10,'肇事后逃逸',12,10000,30);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (11,'未礼让行人',2,0,0);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (12,'驾驶过程手持电话',1,50,0);
insert into violation_type (id,type_name,deduction_score,deduction_amount,detention_day)  values (13,'未系安全带',1,100,0);